on: [push,pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master
    
    # install dependencies
    - name: python install
      run: |
        sudo apt install python3.6-venv
        python3.6 -m venv antenv
        source antenv/bin/activate
        pip3.6 install setuptools
        pip3.6 install -r requirements.txt

    # Archive built app
    - name: archive myapp
      run: |
       zip -r myapp.zip .
        
    # deploy web app
    - uses: azure/webapps-deploy@users/suaggar/containerrelease
      with: 
        app-name: niadakpythonapp  # Replace with your app name
        publish-profile: '${{ secrets.Publish_Profile }}'
        package: './myapp.zip'

    # Add startup command in app service configuration if required

    # Azure logout 
    - name: logout
      run: |
        az logout
